all:
  children:
    servers:
      hosts:
        master.server.home.arpa: {}
        worker-01.x86.server.home.arpa: {}
        worker-02.x86.server.home.arpa: {}
        control.development.home.arpa: {}
    masters:
      hosts:
        master.server.home.arpa: {}
    workers:
      hosts:
        worker-01.x86.server.home.arpa: {}
        worker-02.x86.server.home.arpa: {}
    control-boxes:
      hosts:
        control.development.home.arpa: {}
