all:
  children:
    servers:
      hosts:
        master: {}
        worker-x86-01: {}
        worker-x86-02: {}
        control.development.home.arpa: {}
    development:
      hosts:
        control.development.home.arpa: {}
    control:
      hosts:
        control.development.home.arpa: {}
