---
- name: Roles for servers
  hosts: servers
  ignore_unreachable: true
  become: yes
  roles:
    - shush-ssh
    - utilities-common
    - utilities-development
    - geerlingguy.docker
- name: Roles for masters
  hosts: masters
  become: yes
  roles:
    - interesting-repositories
