---
- name: Make sure package cache is up-to-date
  ansible.builtin.apt:
    update_cache: yes
- name: Install build-essential
  ansible.builtin.apt:
    name: build-essential
    state: present
- name: Install cmake
  ansible.builtin.apt:
    name: cmake
    state: present
