---
- name: Make sure package cache is up-to-date
  ansible.builtin.apt:
    update_cache: yes
- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: present
- name: Install tmux
  ansible.builtin.apt:
    name: tmux
    state: present
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
